Check if locale is a NULL value
* Checking for this NULL value because the Rails (clients) app crashes
with the following message:
/Users/sajoku/.rvm/gems/ruby-2.2.0/bundler/gems/i18n-active_record-2d9a2
2b6a4e5/lib/i18n/backend/active_record/translation.rb:76:in `block in
available_locales': undefined method `to_sym' for nil:NilClass
(NoMethodError)
        from
/Users/sajoku/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_re
cord/relation/delegation.rb:46